name: extract extensions manifests

on:
  push:
    branches: [ "main" ]
  schedule: 
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build and Run with Maven
      run: mvn clean install exec:java -Dexec.mainClass=de.dan1el789.Main
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v3
      with:
        name: extensions-list
        path: extensions.csv

  downloadExtensions:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download math result for job 1
      uses: actions/download-artifact@v3
      with:
        name: extensions-list
    - name: download Extensions
      run: |
        sudo apt install unzip -y
        mkdir manifests
        while IFS="," read -r id name url
        do
          echo "Record is : $id $url"
          curl $url -o "download/$id.zip"
          unzip -d "download/$id" "download/$id.zip"
          cp "download/$id/manifest.json" "manifests/$id.json"
        done < extensions.csv
        cp extensions.csv manifests/extensions.csv
        ls -la
        
    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./manifests
    
